### PR TITLE
updated engine ver from 3.1.0 to 3.2.0

### PR DESCRIPTION
**Pull request by joe-watkins**
Tiny tweak to support Phonegap's recent 3.2.0 update :)

### CODE REVIEW

**Comment by joe-watkins** [comment]
ps. local build process fails after upgrading to 3.2.0 which prompted this pull request. I've tested and things look good.

**Comment by vshabelnyk** [comment]
Yep, the same issue!
Please do this tiny upgrade of version.

**Comment by bgbraga** [comment]
+1

**Comment by lukecarbis** [comment]
I like Rootmale's implementation better: https://github.com/phonegap-build/StatusBarPlugin/pull/11

Using >= is more future proof than a version number change.

**Comment by wildabeast** [comment]
Duplicate of #11, which was merged.

**Pull request closed without merging**
